### ISSUE TITLE
1.18.2点击NPC触发对话报错

### ISSUE THREAD

**Issue by JustinBery** [TabooLib/chemdah#34]
[16:35:56 ERROR]: Could not pass event Begin to Chemdah v0.2.7
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at ink.ptms.chemdah.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[Chemdah-0.2.7.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1613]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at ink.ptms.chemdah.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.core.conversation.Conversation$open$2.invoke$lambda-6$lambda-5$lambda-4(Conversation.kt:126) ~[Chemdah-0.2.7.jar:?]
        at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
        at ink.ptms.chemdah.core.conversation.Conversation$open$2.invoke$lambda-6$lambda-5(Conversation.kt:100) ~[Chemdah-0.2.7.jar:?]
        at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
        at ink.ptms.chemdah.core.conversation.Conversation$open$2.invoke$lambda-6(Conversation.kt:98) ~[Chemdah-0.2.7.jar:?]
        at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
        at ink.ptms.chemdah.core.conversation.Conversation$open$2.invoke(Conversation.kt:85) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.core.conversation.Conversation$open$2.invoke(Conversation.kt:75) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.common5.MirrorKt.mirrorFuture(Mirror.kt:23) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.core.conversation.Conversation.open(Conversation.kt:75) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.core.conversation.Conversation.open$default(Conversation.kt:68) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.core.conversation.ConversationManager$CompatAdyeshach$e$2$1.invoke(ConversationManager.kt:278) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.core.conversation.ConversationManager$CompatAdyeshach$e$2$1.invoke(ConversationManager.kt:277) ~[Chemdah-0.2.7.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98) ~[Chemdah-0.2.7.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/mobs/ActiveMob
        at ink.ptms.chemdah.core.conversation.ConversationManager$CompatMythicMobs.e(ConversationManager.kt:358) ~[Chemdah-0.2.7.jar:?]
        ... 43 more
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.mobs.ActiveMob
        at ink.ptms.chemdah.core.conversation.ConversationManager$CompatMythicMobs.e(ConversationManager.kt:358) ~[Chemdah-0.2.7.jar:?]
        ... 43 more

**Comment by Bkm016** [comment]
Fixed
