### ISSUE TITLE
使用滚轮切换回复内容 开启时出现的错误

### ISSUE THREAD

**Issue by mocha666** [TabooLib/chemdah#41]
```
[16:06:18 ERROR]: Could not pass event PlayerItemHeldEvent to Chemdah v0.2.39
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayOutHeldItemSlot
        at ink.ptms.chemdah.core.conversation.theme.ThemeChat.onItemHeld(ThemeChat.kt:98) ~[Chemdah-0.2.39.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at ink.ptms.chemdah.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Chemdah-0.2.39.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[Chemdah-0.2.39.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2142) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.a(ServerboundSetCarriedItemPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:891) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R3.PacketPlayOutHeldItemSlot
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 32 more
```
使用的服务器核心: `Current: git-Purpur-1632 (MC: 1.18.2)`

**Comment by Bkm016** [comment]
已在 0.2.41 版本修复
