### ISSUE TITLE
开启计分板任务追踪器时发现的问题

### ISSUE THREAD

**Issue by mocha666** [TabooLib/chemdah#43]
```
[00:56:15 WARN]: [Chemdah] Plugin Chemdah v0.2.42 generated an exception while executing task 107
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayOutScoreboardObjective
        at ink.ptms.chemdah.taboolib.module.nms.NMSScoreboardImpl.setupScoreboard(NMSScoreboardImpl.kt:29) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.module.nms.NMSScoreboard.setupScoreboard$default(NMSScoreboard.kt:130) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.module.nms.type.PlayerScoreboard.<init>(PlayerScoreboard.kt:19) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.module.nms.NMSScoreboardKt.sendScoreboard$lambda-1(NMSScoreboard.kt:35) ~[Chemdah-0.2.42.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at ink.ptms.chemdah.taboolib.module.nms.NMSScoreboardKt.sendScoreboard(NMSScoreboard.kt:34) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.addon.AddonTrack$Companion.displayTrackScoreboard(AddonTrack.kt:456) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.addon.AddonTrack$Companion.trackTick$Chemdah(AddonTrack.kt:236) ~[Chemdah-0.2.42.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at ink.ptms.chemdah.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.ScheduleLoader$visit$1$1.invoke(ScheduleLoader.kt:26) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.ScheduleLoader$visit$1$1.invoke(ScheduleLoader.kt:22) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[Chemdah-0.2.42.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:891) ~[?:?]
```

使用的服务器核心: `Current: git-Purpur-1632 (MC: 1.18.2)`

**Comment by Bkm016** [comment]
更新

**Comment by mocha666** [comment]
是核心的问题嘛，上个插件版本还可以使用的
