### ISSUE TITLE
不执行任务时, 后台疯狂刷 ,有时会影响到任务的进行

### ISSUE THREAD

**Issue by mocha666** [TabooLib/chemdah#44]
```

[00:59:01 ERROR]: Could not pass event BlockBreakEvent to Chemdah v0.2.42
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R1/block/data/CraftBlockData
        at ink.ptms.chemdah.core.bukkit.NMSImpl.getBlocKData(NMSImpl.kt:20) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.selector.InferBlock.isBlock(InferBlock.kt:29) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.objective.bukkit.IBlockBreak._init_$lambda-2(IBlockBreak.kt:30) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.objective.Objective.addSimpleCondition$lambda-1(Objective.kt:126) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.objective.Objective.checkCondition(Objective.kt:142) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.QuestLoader.handleTask(QuestLoader.kt:130) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.QuestLoader.handleEvent$lambda-2$lambda-1(QuestLoader.kt:117) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.PlayerProfile.tasks(PlayerProfile.kt:179) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.QuestLoader.handleEvent(QuestLoader.kt:117) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.QuestLoader$register$1.invoke(QuestLoader.kt:98) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.core.quest.QuestLoader$register$1.invoke(QuestLoader.kt:90) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:26) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:26) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[Chemdah-0.2.42.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[Chemdah-0.2.42.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1843) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:891) ~[?:?]
```

补充: 
服务端 purpur-1.18.2
是在玩家破坏方块的时候刷

**Comment by Bkm016** [comment]
更新
