### ISSUE TITLE
任务问题

### ISSUE THREAD

**Issue by JustinBery** [TabooLib/chemdah#48]
任务可以正常用指令接受，但是点击NPC 无法弹出来对话，但有任务的失明效果。

**Comment by JustinBery** [comment]
`[13:20:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chemdah' in plugin Chemdah v0.3.13
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at ink.ptms.chemdah.core.conversation.theme.ThemeChatSettings.<init>(ThemeChatSettings.kt:29) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.core.conversation.theme.ThemeChat.createConfig(ThemeChat.kt:157) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.core.conversation.theme.ThemeChat.createConfig(ThemeChat.kt:48) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.core.conversation.theme.Theme.reloadConfig(Theme.kt:27) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.core.conversation.ConversationLoader.loadAll(ConversationLoader.kt:48) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.api.ChemdahAPI.reloadAll(ChemdahAPI.kt:262) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.module.command.CommandChemdah$reload$1$1.invoke(CommandChemdah.kt:76) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.module.command.CommandChemdah$reload$1$1.invoke(CommandChemdah.kt:75) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:192) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:102) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:115) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:38) ~[Chemdah-0.3.13.jar:?]
        at ink.ptms.chemdah.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:70) ~[Chemdah-0.3.13.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more`

**Comment by Bkm016** [comment]
重新生成配置
