### ISSUE TITLE
[大毛病]开启SQL储存之后接取任务会出现报错

### ISSUE THREAD

**Issue by vdbvbd** [TabooLib/chemdah#61]
database.use设置为SQL之后，玩家进入游戏接取任务就会弹出以下报错。
报错出现后除非重启服务器，否则报错将一直自动弹出。
重启服务器后同一位玩家再次进入服务器不会出现报错，但仍然会在接取任务后出现该类报错。
以下为报错信息
```
[00:35:44] [Craft Scheduler Thread - 35 - Chemdah/WARN]: [Chemdah] INSERT INTO `chemdah_user_data` (`user`, `key`, `value`, `mode`) VALUES (?, ?, ?, ?)
[00:35:44] [Craft Scheduler Thread - 35 - Chemdah/WARN]: [Chemdah] Statement parameter (4): [1, quest.track, 初始任务, 1]
[00:35:44] [Craft Scheduler Thread - 35 - Chemdah/WARN]: [Chemdah] Plugin Chemdah v0.3.22 generated an exception while executing task 3391
java.sql.SQLException: Incorrect string value: '\xE5\x88\x9D\xE5\xA7\x8B...' for column 'value' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.zaxxer.hikari_4_0_3.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[adyeshach-2.0.0-snapshot-11.jar:?]
	at com.zaxxer.hikari_4_0_3.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[adyeshach-2.0.0-snapshot-11.jar:?]
	at ink.ptms.chemdah.taboolib.module.database.Query$executeUpdate$1$call$1.invoke(Query.kt:74) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.module.database.Query$executeUpdate$1$call$1.invoke(Query.kt:70) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.module.database.UtilKt.use(Util.kt:18) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.module.database.Query$executeUpdate$1.call(Query.kt:70) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.module.database.RunTask.run(RunTask.kt:15) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.module.database.Table.insert(Table.kt:52) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.core.database.DatabaseSQL.update$lambda-5(DatabaseSQL.kt:213) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.core.DataContainer.forEach(DataContainer.kt:144) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.core.database.DatabaseSQL.update(DatabaseSQL.kt:203) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.core.database.DatabaseSQL.update(DatabaseSQL.kt:340) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.core.database.Database$Companion.update200$Chemdah(Database.kt:160) ~[Chemdah-0.3.22.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at ink.ptms.chemdah.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.common.platform.ScheduleLoader$visit$1$1.invoke(ScheduleLoader.kt:26) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.common.platform.ScheduleLoader$visit$1$1.invoke(ScheduleLoader.kt:22) ~[Chemdah-0.3.22.jar:?]
	at ink.ptms.chemdah.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[Chemdah-0.3.22.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Bkm016** [comment]
暂时无法解决你的问题，请尝试更新sql版本或重建sql表 🥲
